### ISSUE TITLE
support script arguments or environment variables

### ISSUE THREAD

**Issue by stevecraig** [50ButtonsEach/hax-with-flic-osx#14]
Ideally I want to wire up the actual buttons to something like node-red.  

It would be easier if I could wire all buttons up to a single script and be given command line arguments.
script name clicktype

Then I could just map each function to the same script and have the script build a message from the command line arguments.  This shouldn't break any existing scripts.  if that is an issue it could be set as an environment variable in the calling script FLIC_BUTTON= FLIC_ACTION= 

If you want to make my life even easier you could even have a "default_script" which is executed if no other script is defined.

**Comment by AntonMeier** [comment]
You may want to have a look at [flic-service-osx](https://github.com/50ButtonsEach/flic-service-osx) where you can subscribe to button events over a socket. That would give you a bit more flexibility to do whatever you want, but it would probably require a bit more work.

By the way, I will be updating both repositories pretty soon with some stability fixes for macOS Sierra.

**Comment by stevecraig** [comment]
Thanks for the pointer, that looks to be exactly what I wanted.
