### ISSUE TITLE
Delay on button click

### ISSUE THREAD

**Issue by MoritzSkowronski** [50ButtonsEach/hax-with-flic-osx#18]
Hi,

I am noticing a noticeable delay of about 1-2 seconds when using haxwithflics on both my iMac and Macbook. There is no delay however when using the newer flics app for iOS. Since I use flic mostly for running scripts switching to the newer app is not an option for me.

**Comment by AntonMeier** [comment]
This is very strange. It should be fast. Could you please try and select the "lowLatency" mode and then place the script on buttonDown only? That should give you the best possible latency. If it is still slow after doing this then we need to find out wether the latency is on the button events themselves or if the script is slow. Maybe try a few different scripts for comparison. Let me know how it goes!

**Comment by MoritzSkowronski** [comment]
Hi,

I just tried using button down and it's working with almost no noticeable delay. Using "low latency" improves it even more! :)

Thanks!

**Comment by AntonMeier** [comment]
Cool! Remember that you will always get a little bit more delay on regular click types as it takes a little while to distinguish between click/doubleClick/hold.
