### ISSUE TITLE
Fails to connect!

### ISSUE THREAD

**Issue by jonathan-dejong** [50ButtonsEach/hax-with-flic-osx#5]
Hi,

So I've tried to connect my flic but it does not want to comply! 
I'm a first backer so I have the first batch of flics sent out (also live in Sweden). If that's of any importance.. 

I hit the "scan" button. I press the flic 7 seconds and the app attempts to connect. Within a second or two (after reaching the connecting stage) it fails with the reason:
"The device did not have internet access when the unlock attempt was made."

I'm not even sure what that means? The flic is not connected to any other device and my computer certainly have internet ;) 

I'm running latest OS X on a macbook pro mid 2015. Tried rebooting bluetooth, tried rebooting the computer. 

thanks!

**Comment by AntonMeier** [comment]
Hello, This is strange.

This should not be related to the Flic itself. That error that you see basically means that the computer got an error when it tried to initiate a connection with our backend server for the initial "unlock/verification" of the button.

So if you say that your computer is connected to the internet then I can't really see why this would occur. I'll take a look at it tomorrow and come back with troubleshooting suggestions.

/A

**Comment by jonathan-dejong** [comment]
Hey,

Just heads up. Same issue with a different flic (same batch) on a different internet connection (at work).

**Comment by AntonMeier** [comment]
Ok so I'm quite sure that it is not related to the Flic. What I will try and do today is to build a special version for you that logs the reason for the error. That way we should be able to see what is wrong. Send me an email to anton (at) shortcutlabs.com and I'll try and send it over later today.

Just one thing first though, are you running some kind of HTTPS/SSL proxy on your computer that intercept your network traffic? If that is the case then it will not work.

**Comment by jonathan-dejong** [comment]
Hey,

Thanks I'll shoot you an email right away. 
I have just noticed that this is actually not even limited to my mac. When attempting to connect the flic to my phone (which has an updated version of flic) it fails without specific message "something went wrong" (guessing it's the same issue). 

It seems like the flic button is set in private and wont unlock for either device. Even when removed completely from the flic app.

**Comment by AntonMeier** [comment]
Problem solved.

**Comment by jonathan-dejong** [comment]
Just a reminder: I had the same connection issues using the native flic app.
