### ISSUE TITLE
Sonos integration

### ISSUE THREAD

**Issue by wejstal** [50ButtonsEach/hax-with-flic-osx#8]
Hi,
I have had great success with Sonos integration by using https://github.com/jishi/node-sonos-http-api
combined with a Mac Mini running as a server, however it would be great to access the Sonos directly with shell or AppleScript. Is where anything you can share regarding the Sonos integration you did in the flic app?

**Comment by AntonMeier** [comment]
Hello, I was actually not involved with that integration on the iOS app, but I believe it is some kind of Objective-C framework. However, you can talk to the Sonos directly via shell script. I threw this together just now and it works great:

```
#!/bin/sh

# Play sonos that is available on the local network
# Change the IP address to the IP address of your Sonos.

IP_ADDRESS=192.168.2.25

curl --header 'Content-Type: "text/xml"' --header 'SOAPACTION: "urn:schemas-upnp-org:service:AVTransport:1#Pause"' --data '<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:Pause xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><InstanceID>0</InstanceID><Speed>1</Speed></u:Pause></s:Body></s:Envelope>' http://$IP_ADDRESS:1400/MediaRenderer/AVTransport/Control
```

Remember that you must find out the IP of your sonos first and change that in the script.. If you want to pause then just change Play to Pause on all 3 places. I might throw together a better implementation and upload that later on that contains more stuff like next-song etc..

**Comment by AntonMeier** [comment]
I actually went ahead and added some sonos scripts to this repository. TogglePlay, Play, Pause, Next, Previous. I kind of wanted the scripts for myself anyhow :P

**Comment by wejstal** [comment]
haha great thank you! I was just about to try how to make it toggle play!
